server:
  port: 8082
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true 
hm:
  db:
    database: hm-cart
  swagger:
      title: "黑马商城购物车服务相关接口"
      controller: com.hmall.cart.controller
spring:
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8858 # sentinel dashboard local
      http-method-specify: true # 是否设置请求方式作为资源名称